version = 1

[keybinds]
about_box = "A"

[misc]
# Folder located at:
# Linux: ~/.config/cloudy/aeternum/models
# Mac: ~/Library/Application Support/cloudy/aeternum/models
# Windows: %AppData%\cloudy\aeternum\models
enable_custom_folder = true
